GET  http://localhost:4001/api/dean/getdiploma
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2I4Njk1ZTg1YWNlYTNiYmVkNTM3OTkiLCJpYXQiOjE3NDAxMzg4NDYsImV4cCI6MTc0MDc0MzY0Nn0.6YIWnAbrmPOsJmcZrlRSpYA5UByGqF726R3h31r7XBU








# POST http://localhost:4001/api/auth/signup
# Content-Type: application/json

# {
#     "fullName": "Malay Ko Angeela",
#     "email": "MalaykoAngeela@example.com",
#     "password": "taetatetae",
#     "role": "dean",
#     "department": "COT"
# }
