TODOS SMALL:
  SEARCH DIPLOMAS WILL NOT SHOW WHEN SEARCHED
  FONTS
  PROGRAM SHOULD MATCH
  FORGOT PASSWORD ON LOGIN
  MODAL ON DIGITAL SIGNATURES ON DEAN SIDE(POTENTIALLY DEVY SIDE)
  KAARTEHAN SA MODAL(4/4)
  PRESIDENT KAARTEHAN
  POTENTIAL KAARTEHAN(DIPLOMA ONE BY ONE)

TODOS BIG
  STUDENT FUNCTIONALITY ( MAG REREQUEST )
  SMART CONTRACT (ETO YUNG HYBRID ONE)
  ARCHIVE (DUN TITIGNAN YUNG MGA NAKA STORE)
  ACCEPT REJECT SECTION(DIPLOMA REQUEST)
  BCHAIN UPLOAD WITH PDF AND IPFS INTEGRATION ( ETHERS.JS WEB3.JS AND PDF BLOB AND PINATA )
  SIGNED DIPLOMAS IN ADMIN 
  STATISTICS (CHANGE NAV NAME OF DASHBOARD TO DIPLOMA SOMETHING)
  TEST 11 DIPLOMAS (IF LAGPAS SA KAARTEHAN MAY NEXT BUTTON)

TODO SIDE THINGS
  WEB SOCKET POTENTIAL KAARTEHAN


